// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpELMSkP6dzLGyF7DXmHlM1qDO3_COhr4',
    appId: '1:731145740296:web:78adf5a47552b6b6d371bd',
    messagingSenderId: '731145740296',
    projectId: 'cmsc23-mrzapanta1',
    authDomain: 'cmsc23-mrzapanta1.firebaseapp.com',
    storageBucket: 'cmsc23-mrzapanta1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoQHzXzrsMtwX3O_wwcEwGoVEhfhDyO1Y',
    appId: '1:731145740296:android:64108efdc31dd41fd371bd',
    messagingSenderId: '731145740296',
    projectId: 'cmsc23-mrzapanta1',
    storageBucket: 'cmsc23-mrzapanta1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoR_rcJoqO6lFwAX_OBDFpdXj_bdbUyyw',
    appId: '1:731145740296:ios:9fe472f959ac56fcd371bd',
    messagingSenderId: '731145740296',
    projectId: 'cmsc23-mrzapanta1',
    storageBucket: 'cmsc23-mrzapanta1.appspot.com',
    iosClientId: '731145740296-2rnrdc3783ofibeku79lcj97d7otqhuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoR_rcJoqO6lFwAX_OBDFpdXj_bdbUyyw',
    appId: '1:731145740296:ios:9fe472f959ac56fcd371bd',
    messagingSenderId: '731145740296',
    projectId: 'cmsc23-mrzapanta1',
    storageBucket: 'cmsc23-mrzapanta1.appspot.com',
    iosClientId: '731145740296-2rnrdc3783ofibeku79lcj97d7otqhuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
